### ISSUE TITLE
Skill simulator not working on google chrome Version 66.0.3359.139 (Ufficial build) (64 bit)

### ISSUE THREAD

**Issue by TifaLockhart** [Leayal/swskillsimu#1]
Somedays ago i was able to use the skill sim.From after the skill sim changed skin some days ago,it is not working anymore on my chrome browser.I have java V8 6.6.346.26 installed in my pc and its detected on chrome.If i use it on Edge it works fine but im used to use chrome and i'd like to know what's wrong with it.

**Comment by Leayal** [comment]
Could you give more info about the error?
I mean, which part that is not working?
Provide a screenshot if you don't know how to describe it.

On a side note: you don't need Java installed to be able to use the skill simulator. `Javascript` is not `Java`.
All you need is the a Web Browser and keep it up-to-date, most of modern Web Browsers should have their javascript engine embed into the browser.

**Comment by Leayal** [comment]
Close Issue as it seems to be very old.
