### ISSUE TITLE
SP calculated wrong

### ISSUE THREAD

**Issue by Eden333** [Leayal/swskillsimu#2]
Hi, I'm using the Skill Simulator page on a daily basis and so I thought I can report some bugs.
for Example:

https://swskillsim.leayal.tk/stella/?1=5&2=5&3=1&4=5&7=5&8=2&9=1&10=5&13=1&16=5&17=5&18=2&19=1&20=5&21=3&22=5&23=5&24=3&25=3&26=5&27=5&1002=4&1001=3&1006=2&1007=1&1009=5&1013=3&1011=3&s=0-0-23_1-0-9_2-0-1_3-0-7_4-0-16_5-0-22_0-1-4_1-1-17_2-1-27_3-1-2_4-1-16_5-1-22_0-2-4_1-2-13_2-2-10_3-2-16_4-2-16_5-2-22

on this skill build, there should be 1SP left, but there isn't. Now don't ask me where it's missing but I know it is from Ingame.

I had 1 SP left, then I reskilled my "Beast Party" to 0 so I had 2 SP left and I could invest them into my Basic Attack Mastery 4/5 to -> 5/5 and  there for 0 SP left.

I noticed also that the last two skills on stella, the "awakening skills" are switched.

And when I'm already here, I'd like to make 2 suggestions.
1. It would be nice to have a feature where you can change the option to add/remove the "Job Advancement" or also called "Awakaning", like a "tick box".
2. It would also be nice to see the "Hysteria/Soulnova" skillset for each character.

I am really thankfull to you that you made this site, so I'd like to offer my services to help improve it.
I could translate or add the missing stuff for the "awakening skills" on a basic level, from KR to EN.

Thank you in advance and sorry for bothering if this is no new information.

**Comment by Leayal** [comment]
Thanks for reporting. I'm finding out which skill (I will appreciate anyone can help me with this)....

About the suggestion. First of all, I want to apology if this make you feel disappointed or anything:
* ~~For the `1`: That is what I thought of when starting to add the advancement skills, but I was so lazy ~~and lose motivation for the game~~ so I can barely have any will to make it.~~
* For the `2`: SoulNova-skill is unlikely possible to invest SP to it, so I skipped it. And, the skill tree doesn't even have completed text for skill effects, descriptions (because I can't read Japanese or Korean, in addition, the same reason above: lazy + motivation issue), and put SoulNova skill without its name or description is not good.

I'm now only maintain the skill tree when the game has skill changes, or the tree has wrong infos, bugs.

**Comment by Eden333** [comment]
Thank you answering, I thought you were no longer active.
I would LOVE to help with these kind of things I suggested and I kinda already knew the reason why you didn't add them in the first place (I'm like that too ^^) . But first I have to sort my RL before I start doing stuff like this, I update as soon as I get a breakthrough on anything...

**Comment by Leayal** [comment]
@Crash333 I made up my mind and decided to implement character class selection. If you detect any odd behaviors and suspect it as a bug, feel free to report it.

**Comment by Eden333** [comment]
WOW, sure I will, thank you!

**Comment by Eden333** [comment]
I found it somewhere
it's at lvl 30
https://imgur.com/a/QW67NQJ
https://leayal.github.io/swskillsimu/stella/?lv=30&1=2&2=5&3=1&4=5&6=3&7=5&8=2&9=3&16=4&17=2&19=2&20=1&1002=5&1001=2&1006=2&1007=1&1009=4&1011=2&c=0
you have 70SP
instead of 69

I'm sorry, I didn't keep track of the SP you get per lvl
I will have to redo it i guess but I atleast know now where it is

**Comment by Leayal** [comment]
Thank you for your help.
And a tip: usually it increase 2SP per level, however, some +10 will be different, perhaps each 5, too.
For example: lv35,45,55 increase 5SP. And Lv20, 40 increase 10SP.

However, I don't know myself if those are correct or not. I abadoned the game long ago and having issues to ask for information about these....

**Comment by Eden333** [comment]
ya I will tell you if i know more, I'm addicted o_O
I only got 4 more days left of work then I can and WILL play more
so don't worry.

**Comment by Crash333** [comment]
oh did you update it already?

**Comment by Leayal** [comment]
I've made no commits. Last commit was 2 months ago.
So, no, I didn't.

**Comment by Eden333** [comment]
sry I'm just blind, it's a skill not the SP
I'm trying to find it rn
I will update you in a bit

**Comment by Eden333** [comment]
I found it
It's Whirlwind from 2 to 3.
1SP instead of 2SP
I made a commit

**Comment by Leayal** [comment]
I don't see any pull requests in this repo or any commits to your forked repo.
Did you `push` the commit to github yet?

**Comment by Eden333** [comment]
ya? its called patch-2  or patch-3
I did it twice...

**Comment by Eden333** [comment]
do I need to make a pull request or what?

**Comment by Leayal** [comment]
Oh...sorry, I didn't check for branch, I thought you were working on master one.
Heheh....Checking now.

**Comment by Eden333** [comment]
I would if I could ^^

**Comment by Leayal** [comment]
Wow, thanks. I will close this issue as it is fixed now.
*And put your github name on the leaderboard, too.*

**Comment by Eden333** [comment]
it's still doing 2sp instead of 1?
http://up.p4ul.cc/crash333/0d06838111582c95dc3d4f7e68857c75.mp4
or am I being stupid? 
the link is a gif i made real quick, no virus...
edit: leaderboard?
you mean the credit page?

**Comment by Leayal** [comment]
Uh...SourceCode is literally `source`.
The github page which host the tree is using `docs` folder. Which require me to "compile" (It's not literally compile) from source to apply changes to the web.

It should be applied by now.
Commit: [Fix Stella skill tree: Whirl Dance](https://github.com/Leayal/swskillsimu/commit/529ab749f0e11a482751f19d2c54d08f2816af61)

**Comment by Eden333** [comment]
sry, I don't know how github work yet...
my discord name is: "Eden~♡#2724" if you wanted to know that...

**Comment by Leayal** [comment]
First for everything.
Though this `compiling` things is because of me, the rest is github.

**Comment by Eden333** [comment]
but how do I find the user id thingy? or is that not discord?

**Comment by Leayal** [comment]
Enable `Developer Mode`, then right click on your username and select `Copy ID`.
Detail: [Developer Mode and ObjectID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)

**Comment by Eden333** [comment]
119560532947632134
thank you for everything so far
