### ISSUE TITLE
Should the simulator have skill preview?

### ISSUE THREAD

**Issue by Leayal** [Leayal/swskillsimu#3]
Just as the issue's title. I want to hear the users' preference on this matter.

* Should the simulator have skill preview?
  * If it should, which kind of preview should it use? (see below):
    * Video preview (which will be auto-play) when hover the mouse on a skill.
    * ~~Static-image when hover the mouse on a skill.~~ (I changed my mind. I don't see a point to preview a skill with just a non-animated image. Even if it's animated, GIF for example, a video is still much cheaper than GIF)
    * Both, and let the user change the setting to their preference. *If this, I'll try my best but it may take quite a while.*

**Comment by Eden333** [comment]
you mean like, in the game whe you hover over your skill tree?
ya sure, if you wanna do it

**Comment by Leayal** [comment]
Implemented.
