### ISSUE TITLE
Stella Skills switched

### ISSUE THREAD

**Issue by Eden333** [Leayal/swskillsimu#6]
Hey there it's me again,
Wolf's Showtime & Reckless Princess are switched on usable skills.
What I mean with that it, If you try to put "Reckless Princess" into the Slot assignment, it's not there but, "Wolf's Showtime" is there, and it shouldn't be there, because it's an Aerial Skill.
I posted a pull request for it, if that's the correct one... because I don't know about the compiler thingy you said last time.

**Comment by Leayal** [comment]
To clarify:
- You mean the skill simulator is wrong when Reckless Princess was assignable?
- Reckless Princess is an aerial skill?

**Comment by Eden333** [comment]
Reckless princess is not assignable but wolf's Showtime is
And yes reckless princess is an aerial skill like beast parade

**Comment by Leayal** [comment]
- Their skill positions on the tree are still correct?

Your correction is correct. However, default value of assignable was `true`, so if you omit (and I recommend you to) that assignable property, the simulator will take that skill as assignable. Only `false` value need to be declared.

**Comment by Eden333** [comment]
Oh ok, I will have a look when I'm back on my pc

**Comment by Eden333** [comment]
![image](https://user-images.githubusercontent.com/18154402/49727744-4d1c3b80-fc71-11e8-81c9-eded66385b63.png)
yup those 2 are switched around, I will post a updated pull request.

**Comment by Leayal** [comment]
Thank you again for the fix and everything.
I will close this issue as it is fixed and applied.

**Comment by Eden333** [comment]
Hi there, I know this is a closed topic, but I found no other way to contact you.
Do you maybe have discord or a Email Address i could reach out to?

**Comment by Leayal** [comment]
I have discord account. It's `Dramiel Leayal#8799`.

**Comment by Eden333** [comment]
for some reason, I cannot reach you anymore on that account, did you make a new one?
would be great if i could message you.
